### PR TITLE
This branch contains small changes that are not alert related.

### PR DESCRIPTION
**Pull request by tzachi-dar**

### CODE REVIEW

**Comment by StephenBlackWasAlreadyTaken** [comment]
Cool, so the idea here is having the timestamps be exactly the same on transmitter data and bg data?

**Comment by tzachi-dar** [comment]
Yes, that is correct.
Please also note, that since I query the different android tvs once in 30
seconds there can be a real differance in time between the two, so it is
better to have the exact same time.

Thanks
Tzachi

**Comment by StephenBlackWasAlreadyTaken** [comment]
Definitely, and looks good, just going to give it one more look over but definitely looks mergeable

**Comment by tzachi-dar** [comment]
Thanks.

I believe that you also need to merge this into the master of
dexdrip/eperimental.

Tzachi

**Comment by StephenBlackWasAlreadyTaken** [comment]
Good call, just pushed it over, Ill need to remember to be in that habbit!

On Wed, Feb 18, 2015 at 5:15 PM, tzachi-dar <notifications@github.com>
wrote:

> Thanks.
>
> I believe that you also need to merge this into the master of
> dexdrip/eperimental.
>
> Tzachi
>
> On Wed, Feb 18, 2015 at 5:28 PM, Stephen Black <notifications@github.com>
> wrote:
>
> > Merged #71
> > <https://github.com/StephenBlackWasAlreadyTaken/DexDrip/pull/71>.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/StephenBlackWasAlreadyTaken/DexDrip/pull/71#event-237723670
> >
>
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/StephenBlackWasAlreadyTaken/DexDrip/pull/71#issuecomment-74959937>
> .
>



-- 


Stephen Black

Software Engineer


  ShopKeep | 800.820.9814

       shopkeep.com | facebook <https://www.facebook.com/ShopKeepPOS>
twitter <https://twitter.com/shopkeep> linkedin
<http://www.linkedin.com/company/shopkeep-pos>

**Pull request merged**
