### PR TITLE
Cancel PR 48 and use this one.

### PR DESCRIPTION
**Pull request by jstevensog**
I found more typos and a file that had not been put into the git repository from when I manually merged your other changes.
Fixed error in setSerialDataToTransmitterRawData in DexCollectionService, where the data packet block was looking at the wrong byte to find the transmitter ID.  I make this mistake a lot when I copy and paste the correction code from the beacon packet block.
Added \assets\migrations\migrations.sql, which I missed from when I manually merged your later (est?) commit.
Corrected the queuing code in DexCollectionService that was throwing an exception in BluetoothGatt.
Now very reliable at dealing with messages, even if the time stamping on the graph is jittery.  No longer putting multiple values on a single time stamp.
Deals with wixel sleep, beacon on wake, and beacon on sleep much better.

### CODE REVIEW

**Comment by StephenBlackWasAlreadyTaken** [comment]
Unfortunately there are a lot of merge conflicts (also it seems to merge in some commits from the gh-pages branch)

**Comment by StephenBlackWasAlreadyTaken** [comment]
Im going to load this up tonight to give it a shot!! You may want to rebase some of those commits that have to do with github pages out
Actually it looks like it may have originally been forked from the github pages branch

**Comment by jstevensog** [comment]
Yeah. Forked.it from github. But I am bit at all familiar with github. Will
try rebasing it. Will let you know how I go.
Cheers

**Comment by jstevensog** [comment]
Closing.  Trying to rebase my repo to remove a lot of commits and stuff before creating a new one.

**Pull request closed without merging**
